nodes:
- input.recorded:
    input_dir: "/Users/ngleeping/Desktop/input"
- model.yolo:
    model_type: v4tiny
- heuristic.fps:
    fps_log_display: True
# - output.csv_writer:
#     stats_to_track: ["fps"]
