name: Premerge Checks
on: [push, pull_request]

jobs:
  check_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cicd_requirements.txt
      - name: Run lint checks
        uses: ./.github/actions/linting-checks  # note only works after checkout@v2
      - name: Run unit tests
        run: bash ./scripts/run_tests.sh unit
